const uint GEO_ERROR_NONE = 0;
const uint GEO_ERROR_INVALID_SOURCE_ID = 1;
const uint GEO_ERROR_INVALID_TARGET_ID = 2;
const uint GEO_ERROR_INVALID_DT = 3;
const uint GEO_ERROR_CONTACT_LIST_MISSING = 4;
const uint GEO_ERROR_PARTICLE_OUT_OF_BOUNDS = 5;
