// Generated by tools/ExportForceDynamicsSimpleGLSL.py.
// Shared material color-mode mapping for Vulkan particle rendering.

#if defined(DEBUG)
    #extension GL_EXT_debug_printf : enable
#endif
vec3 hsv2rgb(in vec3 hsv);
vec3 colorizeVelocity(float v_ang, float sat, float val);
uint material_color_mode(uint materialID);
vec4 material_color(uint materialID);
uint material_debug_visible(uint materialID);
vec4 material_debug_color(uint materialID);
bool color_map_is_photon(uint index);
vec4 lumens_color(uint index, vec4 baseColor);
vec4 color_from_mode(uint index, uint colorMode, vec4 baseColor);

vec4 color_map(uint index)
{
    uint materialID = uint(round(P[index].material_id));
    if (color_map_is_photon(index))
        return lumens_color(index, material_color(materialID));
    uint colorMode = material_color_mode(materialID);
    vec4 baseColor = material_color(materialID);
    return color_from_mode(index, colorMode, baseColor);

}

bool color_map_is_photon(uint index)
{
    return int(round(P[index].ptype)) == -2;
}

uint material_color_mode(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].colorMode;
    }

    return COLOR_MODE_COLLISION;
}

vec4 material_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].color;
    }

    return vec4(1.0, 1.0, 1.0, 1.0);
}

uint material_debug_visible(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].debugVisible;
    }

    return 0u;
}

vec4 material_debug_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].debugColor;
    }

    return vec4(1.0, 1.0, 1.0, 1.0);
}

vec4 lumens_color(uint index, vec4 baseColor)
{
    if (P[index].contactCount == 0u && uint(P[index].colFlg) == 0u)
    {
        uint materialID = uint(round(P[index].material_id));
        if (material_debug_visible(materialID) == 1u)
            return material_debug_color(materialID);
        return vec4(0.0, 0.0, 0.0, 0.0);
    }

    uint materialID = uint(round(P[index].material_id));
    return material_color(materialID);
}

vec4 color_from_mode(uint index, uint colorMode, vec4 baseColor)
{
    if (colorMode == COLOR_MODE_VELOCITY)
    {
        float velocityAngle = ShaderFlags.positionBuffer == 0u
            ? P[index].VelRadA.w
            : P[index].VelRadB.w;
        return vec4(colorizeVelocity(velocityAngle, HSV_SAT, HSV_VAL), baseColor.a);
    }

    if (colorMode == COLOR_MODE_COLLISION)
    {
        if (uint(P[index].colFlg) == 1u)
            return vec4(colcolor, 1.0);
        return vec4(ncolcolor, 1.0);
    }

    if (colorMode == COLOR_MODE_SOLID)
        return baseColor;

    if (colorMode == COLOR_MODE_LUMENS)
        return lumens_color(index, baseColor);

    return vec4(1.0, 1.0, 1.0, 1.0);
}

vec3 hsv2rgb(in vec3 hsv)
{
///H, S and V input range = 0 - 1.0
//R, G and B output range = 0 - 255
    float H = hsv.r;
    float S = hsv.g;
    float V = hsv.b;
    float var_r;
    float var_g;
    float var_b;
    float R = 0;
    float G = 0;
    float B = 0;

    vec3 ret_clr = vec3(0.0);
    if ( S == 0 )
    {
       R = V * 255;
       G = V * 255;
       B = V * 255;
    }
    else
    {
       float var_h = H * 6;
       if ( var_h == 6 ) var_h = 0 ;
       //H must be < 1
       float var_i = int( var_h );             //Or ... var_i = floor( var_h )
       float var_1 = V * ( 1 - S );
       float var_2 = V * ( 1 - S * ( var_h - var_i ) );
       float var_3 = V * ( 1 - S * ( 1 - ( var_h - var_i ) ) );

       if( var_i == 0 )
       {
            var_r = V;
            var_g = var_3 ;
            var_b = var_1;
        }
       else if ( var_i == 1 )
       {
            var_r = var_2 ;
            var_g = V     ;
            var_b = var_1;
        }
       else if ( var_i == 2 )
       {
            var_r = var_1 ;
            var_g = V     ;
            var_b = var_3 ;
        }
       else if ( var_i == 3 )
       {
            var_r = var_1 ;
            var_g = var_2 ;
            var_b = V ;
        }
       else if ( var_i == 4 )
       {
            var_r = var_3 ;
            var_g = var_1 ;
            var_b = V;
        }
       else
       {
            var_r = V     ;
            var_g = var_1 ;
            var_b = var_2 ;
        };

       R = var_r * 255;
       G = var_g * 255;
       B = var_b * 255;
    }
    ret_clr = vec3(R/255,G/255,B/255);
    return ret_clr;
}

vec3 colorizeVelocity(float v_ang, float sat, float val)
{
    float hue = fract(v_ang / 6.28318530718);
    return hsv2rgb(vec3(hue, clamp(sat, 0.0, 1.0), clamp(val, 0.0, 1.0)));
}
