// Generated by tools/ExportForceDynamicsSimpleGLSL.py.
// Shared material color-mode mapping for Vulkan particle rendering.

#if defined(DEBUG)
    #extension GL_EXT_debug_printf : enable
#endif
vec3 hsv2rgb(in vec3 hsv);
vec3 colorizeVelocity(float v_ang, float sat, float val);
uint material_color_mode(uint materialID);
uint material_color_map(uint materialID);
float material_point_size(uint materialID);
uint material_capture_angle_offset(uint materialID);
uint material_capture_angle_count(uint materialID);
vec4 material_color(uint materialID);
vec4 material_collision_color(uint materialID);
vec4 material_non_collision_color(uint materialID);
uint material_debug_visible(uint materialID);
vec4 material_debug_color(uint materialID);
bool color_map_is_photon(uint index);
vec4 lumens_color(uint index, vec4 baseColor);
vec4 value_from_color_mode(uint index, uint materialID, uint colorMode, vec4 baseColor);
bool capture_angle_matches(uint materialID, float angle);
float signed_angle_delta(float angle, float center);
vec4 color_from_color_map(vec4 value, uint materialID, uint colorMode, uint colorMap, vec4 baseColor);

vec4 color_map(uint index)
{
    uint materialID = uint(round(P[index].material_id));
    if (color_map_is_photon(index))
        return lumens_color(index, material_color(materialID));
    uint colorMode = material_color_mode(materialID);
    uint colorMap = material_color_map(materialID);
    vec4 baseColor = material_color(materialID);
    vec4 value = value_from_color_mode(index, materialID, colorMode, baseColor);
    return color_from_color_map(value, materialID, colorMode, colorMap, baseColor);

}

bool color_map_is_photon(uint index)
{
    int ptype = int(round(P[index].ptype));
    return ptype == -2 || ptype == -3;
}

uint material_color_mode(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].colorMode;
    }

    return COLOR_MODE_COLLISION;
}

uint material_color_map(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].colorMap;
    }

    return COLOR_MAP_SOLID;
}

float material_point_size(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return max(MATERIAL_PROPERTIES[ii].pointSize, 1.0);
    }

    return max(point_size, 1.0);
}

uint material_capture_angle_offset(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].captureAngleOffset;
    }

    return 0u;
}

uint material_capture_angle_count(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].captureAngleCount;
    }

    return 0u;
}

vec4 material_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].color;
    }

    return vec4(1.0, 1.0, 1.0, 1.0);
}

vec4 material_collision_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].collisionColor;
    }

    return vec4(1.0, 0.0, 0.0, 1.0);
}

vec4 material_non_collision_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].nonCollisionColor;
    }

    return vec4(0.0, 1.0, 0.0, 1.0);
}

uint material_debug_visible(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].debugVisible;
    }

    return 0u;
}

vec4 material_debug_color(uint materialID)
{
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii)
    {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID)
            return MATERIAL_PROPERTIES[ii].debugColor;
    }

    return vec4(1.0, 1.0, 1.0, 1.0);
}

vec4 lumens_color(uint index, vec4 baseColor)
{
    if (P[index].contactCount == 0u && uint(P[index].colFlg) == 0u)
    {
        uint materialID = uint(round(P[index].material_id));
        if (material_debug_visible(materialID) == 1u)
            return material_debug_color(materialID);
        return vec4(0.0, 0.0, 0.0, 0.0);
    }

    uint materialID = uint(round(P[index].material_id));
    return material_color(materialID);
}

vec4 value_from_color_mode(uint index, uint materialID, uint colorMode, vec4 baseColor)
{
    if (colorMode == COLOR_MODE_VELOCITY_ANGLE)
    {
        float velocityAngle = ShaderFlags.positionBuffer == 0u
            ? P[index].VelRadA.w
            : P[index].VelRadB.w;
        return vec4(velocityAngle, 0.0, 0.0, baseColor.a);
    }

    if (colorMode == COLOR_MODE_COLLISION)
    {
        if (uint(P[index].colFlg) == 1u)
            return material_collision_color(materialID);
        return material_non_collision_color(materialID);
    }

    if (colorMode == COLOR_MODE_SOLID)
        return baseColor;

    if (colorMode == COLOR_MODE_LUMENS)
        return lumens_color(index, baseColor);

    return vec4(1.0, 1.0, 1.0, 1.0);
}

float signed_angle_delta(float angle, float center)
{
    const float TWO_PI = 6.28318530718;
    return mod(angle - center + 3.14159265359, TWO_PI) - 3.14159265359;
}

bool capture_angle_matches(uint materialID, float angle)
{
    uint captureCount = material_capture_angle_count(materialID);
    uint captureOffset = material_capture_angle_offset(materialID);
    for (uint ii = 0u; ii < captureCount; ++ii)
    {
        uint captureIndex = captureOffset + ii;
        if (captureIndex >= CAPTURE_ANGLE_COUNT)
            break;
        float delta = signed_angle_delta(angle, CAPTURE_ANGLES[captureIndex].center);
        if (delta >= 0.0 && delta <= CAPTURE_ANGLES[captureIndex].plusRange)
            return true;
        if (delta < 0.0 && -delta <= CAPTURE_ANGLES[captureIndex].minusRange)
            return true;
    }

    return false;
}

vec4 color_from_color_map(vec4 value, uint materialID, uint colorMode, uint colorMap, vec4 baseColor)
{
    float scalar = clamp(value.x, 0.0, 1.0);

    if (colorMap == COLOR_MAP_HSV)
    {
        if (
            colorMode == COLOR_MODE_VELOCITY_ANGLE &&
            material_capture_angle_count(materialID) > 0u &&
            !capture_angle_matches(materialID, value.x)
        )
        {
            return vec4(0.0, 0.0, 0.0, value.a);
        }
        return vec4(
            colorizeVelocity(
                scalar,
                VELOCITY_ANGLE_COLOR_SAT,
                VELOCITY_ANGLE_COLOR_VAL
            ),
            value.a
        );
    }

    if (colorMap == COLOR_MAP_GRAYSCALE)
        return vec4(vec3(scalar), value.a);

    if (colorMap == COLOR_MAP_HEAT)
        return vec4(clamp(vec3(2.0 * scalar, 2.0 * scalar - 0.5, 2.0 * scalar - 1.0), 0.0, 1.0), value.a);

    if (colorMap == COLOR_MAP_SOLID)
        return value;

    return baseColor;
}

vec3 hsv2rgb(in vec3 hsv)
{
///H, S and V input range = 0 - 1.0
//R, G and B output range = 0 - 255
    float H = hsv.r;
    float S = hsv.g;
    float V = hsv.b;
    float var_r;
    float var_g;
    float var_b;
    float R = 0;
    float G = 0;
    float B = 0;

    vec3 ret_clr = vec3(0.0);
    if ( S == 0 )
    {
       R = V * 255;
       G = V * 255;
       B = V * 255;
    }
    else
    {
       float var_h = H * 6;
       if ( var_h == 6 ) var_h = 0 ;
       //H must be < 1
       float var_i = int( var_h );             //Or ... var_i = floor( var_h )
       float var_1 = V * ( 1 - S );
       float var_2 = V * ( 1 - S * ( var_h - var_i ) );
       float var_3 = V * ( 1 - S * ( 1 - ( var_h - var_i ) ) );

       if( var_i == 0 )
       {
            var_r = V;
            var_g = var_3 ;
            var_b = var_1;
        }
       else if ( var_i == 1 )
       {
            var_r = var_2 ;
            var_g = V     ;
            var_b = var_1;
        }
       else if ( var_i == 2 )
       {
            var_r = var_1 ;
            var_g = V     ;
            var_b = var_3 ;
        }
       else if ( var_i == 3 )
       {
            var_r = var_1 ;
            var_g = var_2 ;
            var_b = V ;
        }
       else if ( var_i == 4 )
       {
            var_r = var_3 ;
            var_g = var_1 ;
            var_b = V;
        }
       else
       {
            var_r = V     ;
            var_g = var_1 ;
            var_b = var_2 ;
        };

       R = var_r * 255;
       G = var_g * 255;
       B = var_b * 255;
    }
    ret_clr = vec3(R/255,G/255,B/255);
    return ret_clr;
}

vec3 colorizeVelocity(float v_ang, float sat, float val)
{
    float hue = fract(v_ang / 6.28318530718);
    return hsv2rgb(vec3(hue, clamp(sat, 0.0, 1.0), clamp(val, 0.0, 1.0)));
}
