#ifndef LIGHTING_PARTICLE_GLSL
#define LIGHTING_PARTICLE_GLSL
#define LIGHTING_PARTICLE_STRUCT_AVAILABLE 1

// Generated by tools/ExportForceDynamicsSimpleGLSL.py.
// FPML-only particle layout.  This mirrors the C++ LightingParticle struct and
// deliberately replaces particle.glsl for lighting applications.

struct lstr {
    uint pindex;
    uint ploc;
    uint fill;
};

struct Particle {
    vec4 PosLocA;              // xyz=position, w=active flag: 0 active, 1 inactive
    vec4 PosLocB;              // xyz=alternate position buffer, w=active flag
    vec4 VelRadA;              // xyz=velocity, w=velocity angle
    vec4 VelRadB;              // xyz=velocity, w=velocity angle

    vec4 Data;                 // x=radius, y=collision_stiffness_q, z=reserved, w=state/flags
    vec4 parms;                // x=mass, yzw=source-owned recoverable internal momentum

    lstr CornerList[8];

    uint contactCount;         // active entries in contacts
    uint colFlg;               // 1 if in collision, 0 if not

    float ptype;               // runtime particle type copied from binary pdata.ptype
    float material_id;         // material/color source

    vec4 initial_pos_birth;    // xyz=original slot position, w=original release frame
    vec4 initial_vel_energy;   // xyz=original photon velocity, w=reserved
    vec4 photon_transport;     // x=lived frames, y=cycle count, z=flags, w=reserved
};

struct boundStruct {
    bool inBX;
    bool inBY;
    bool inBZ;
};

layout(std430,binding = 4) buffer ParticleSSBOOut {
    Particle P[];
};

#endif
