#ifndef PHOTONS_GLSL
#define PHOTONS_GLSL

// Generated by tools/ExportForceDynamicsSimpleGLSL.py.
// Optical photon helpers shared by generated simple Vulkan force shaders.

uint GetParticleType(uint particleID)
{
    uint materialID = uint(round(P[particleID].material_id));
    for (uint ii = 0u; ii < MATERIAL_PROPERTY_COUNT; ++ii) {
        if (MATERIAL_PROPERTIES[ii].materialID == materialID) {
            return MATERIAL_PROPERTIES[ii].particleType;
        }
    }
    return PARTICLE_TYPE_REGULAR;
}

bool IsPhotonParticle(uint particleID)
{
    return GetParticleType(particleID) == PARTICLE_TYPE_PHOTON;
}

bool ShouldSkipParticlePair(uint sourceID, uint targetID)
{
    bool sourcePhoton = IsPhotonParticle(sourceID);
    bool targetPhoton = IsPhotonParticle(targetID);
    return (sourcePhoton && targetPhoton) || (!sourcePhoton && targetPhoton);
}

vec3 ReflectFixedSpeed(vec3 velocity, vec3 normal)
{
    float speed = length(velocity);
    float normalLength = length(normal);
    if (speed <= 0.0 || normalLength <= 0.0) {
        return velocity;
    }

    vec3 unitNormal = normal / normalLength;
    vec3 reflected = velocity - 2.0 * dot(velocity, unitNormal) * unitNormal;
    float reflectedLength = length(reflected);
    if (reflectedLength <= 0.0) {
        return velocity;
    }
    return speed * reflected / reflectedLength;
}

struct PhotonParticleReflection
{
    bool reflected;
    vec3 velocity;
    vec3 position;
};

vec3 PhotonStartPosition(uint particleID)
{
    return uint(ShaderFlags.positionBuffer) == 0u
        ? P[particleID].PosLocA.xyz
        : P[particleID].PosLocB.xyz;
}

vec3 PhotonStartVelocity(uint particleID)
{
    return uint(ShaderFlags.positionBuffer) == 0u
        ? P[particleID].VelRadA.xyz
        : P[particleID].VelRadB.xyz;
}

PhotonParticleReflection NoPhotonParticleReflection(uint sourceID)
{
    return PhotonParticleReflection(
        false,
        PhotonStartVelocity(sourceID),
        PhotonStartPosition(sourceID));
}

PhotonParticleReflection RecordPhotonParticleReflection(
    uint sourceID,
    uint targetID,
    vec3 normal,
    float hitT)
{
    float dt = ShaderFlags.dt;
    vec3 targetPosition = PhotonStartPosition(targetID);
    vec3 targetVelocity = PhotonStartVelocity(targetID);
    vec3 sourceVelocity = PhotonStartVelocity(sourceID);
    vec3 reflectedVelocity = ReflectFixedSpeed(sourceVelocity, normal);
    float boundedHitT = clamp(hitT, 0.0, 1.0);
    vec3 targetHitPosition = targetPosition + targetVelocity * dt * boundedHitT;
    float sourceRadius = P[sourceID].Data.x;
    float targetRadius = P[targetID].Data.x;
    float contactRadius = sourceRadius + targetRadius;
    vec3 hitPosition = targetHitPosition - normal * contactRadius;
    float remainingDt = dt * (1.0 - boundedHitT);
    float exitEpsilon = max(1.0e-12, sourceRadius * 0.01);
    vec3 outputPosition =
        hitPosition + reflectedVelocity * remainingDt - normal * exitEpsilon;
    return PhotonParticleReflection(true, reflectedVelocity, outputPosition);
}

bool TryPhotonParticleReflection(
    uint sourceID,
    uint targetID,
    out PhotonParticleReflection reflection)
{
    reflection = NoPhotonParticleReflection(sourceID);
    if (!IsPhotonParticle(sourceID) || IsPhotonParticle(targetID)) {
        return false;
    }

    float dt = ShaderFlags.dt;
    if (dt <= 0.0) {
        return false;
    }

    vec3 sourcePosition = PhotonStartPosition(sourceID);
    vec3 targetPosition = PhotonStartPosition(targetID);
    vec3 sourceVelocity = PhotonStartVelocity(sourceID);
    vec3 targetVelocity = PhotonStartVelocity(targetID);
    vec3 relativeMotion = (sourceVelocity - targetVelocity) * dt;
    float motionLengthSq = dot(relativeMotion, relativeMotion);
    if (motionLengthSq <= 1.0e-12) {
        return false;
    }

    vec3 startDelta = sourcePosition - targetPosition;
    float sourceRadius = P[sourceID].Data.x;
    float targetRadius = P[targetID].Data.x;
    float contactRadius = sourceRadius + targetRadius;
    float contactRadiusSq = contactRadius * contactRadius;
    float startDistanceSq = dot(startDelta, startDelta);
    float hitT = 0.0;
    vec3 normal = vec3(1.0, 0.0, 0.0);

    if (startDistanceSq < contactRadiusSq) {
        float centerDistance = sqrt(max(startDistanceSq, 0.0));
        if (centerDistance > 1.0e-12) {
            normal = -startDelta / centerDistance;
        }
    } else {
        float a = motionLengthSq;
        float b = 2.0 * dot(startDelta, relativeMotion);
        float c = startDistanceSq - contactRadiusSq;
        float discriminant = b * b - 4.0 * a * c;
        if (discriminant < 0.0) {
            return false;
        }
        float sqrtDiscriminant = sqrt(discriminant);
        float firstT = (-b - sqrtDiscriminant) / (2.0 * a);
        float secondT = (-b + sqrtDiscriminant) / (2.0 * a);
        if (firstT >= 0.0 && firstT <= 1.0) {
            hitT = firstT;
        } else if (secondT >= 0.0 && secondT <= 1.0) {
            hitT = secondT;
        } else {
            return false;
        }

        vec3 hitDelta = startDelta + relativeMotion * hitT;
        float centerDistance = length(hitDelta);
        if (centerDistance > 1.0e-12) {
            normal = -hitDelta / centerDistance;
        }
    }

    reflection = RecordPhotonParticleReflection(
        sourceID,
        targetID,
        normal,
        hitT);
    return true;
}

#endif
